# App Engine configuration for backend
runtime: nodejs18

env_variables:
  NODE_ENV: production
  PORT: 8080
  # These will be overridden by environment variables set in GCP Console
  # FIREBASE_PROJECT_ID: kalasetu-e55c4
  # FIREBASE_CLIENT_EMAIL: (set in Cloud Console)
  # FIREBASE_PRIVATE_KEY: (set in Cloud Console)
  # GCLOUD_STORAGE_BUCKET: kalasetu-e55c4.firebasestorage.app
  # GEMINI_API_KEY: (set in Cloud Console)
  # STRIPE_SECRET_KEY: (set in Cloud Console)

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
  - url: /.*
    script: auto
    secure: always

